### ISSUE TITLE
[Feature] Per-user autoskip option

### ISSUE THREAD

**Issue by hugo-id** [ConfusedPolarBear/intro-skipper#110] opened 2022-11-19 01:01 UTC
**Describe the feature you'd like added**
The ability for each user to decide whether or not they want intros to be automagically skipped

**Additional context**
Some of my friends love them, some hate them, and due to the unreliability of the "skip intro" button appearing this toggle is likely the only way I'll be able to keep everybody happy until Jelly finally decides to incorporate your plugin into its core functionality.

Thanks for your work btw, it's bloody amazing work

**Comment by antoinedelia** [comment] 2022-11-19 22:40
I think this is already opened here: https://github.com/ConfusedPolarBear/intro-skipper/issues/18

**Comment by ConfusedPolarBear** [comment] 2022-11-22 08:51
Duplicate of #18

**Closed by ConfusedPolarBear** 2022-11-22 08:51 UTC
Labels: enhancement
