### ISSUE TITLE
Per-user configuration

### ISSUE THREAD

**Issue by raingloom** [ConfusedPolarBear/intro-skipper#146] opened 2023-02-28 20:05 UTC
**Describe the feature you'd like added**
It should be possible to configure the add-on for each user in the settings menu.

**Additional context**
I use a friend's server and they configured this addon to auto-skip (or maybe it was auto-skipping due to a bug even though it wasn't supposed to?) but now disabled it for my sake.

It should be possible to have both our preferences respected instead of forcing a global config on everyone.

Having a per-show or per-session config could also be good ideas, but I'm not sure how difficult those are to implement.  Just throwing the idea out there.

**Comment by ConfusedPolarBear** [comment] 2023-03-03 04:13
Duplicate of #18

**Closed by ConfusedPolarBear** 2023-03-03 04:13 UTC
Labels: enhancement
